root: ./

redirects:
  the-iotex-stack/basic-concepts/address-conversion: builders/reference-docs/native-iotex-development/address-conversion.md
  developer/smart-contracts/issue-tokens: builders/defi/deploy-tokens.md
